name = "liviubucel-website"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat_v2" ]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[vars]
SANITY_PROJECT_ID="8atrdwjk"
SANITY_DATASET="production"
CONTACT_TO_EMAIL="contact@liviubucel.com"
CONTACT_FROM_EMAIL="noreply@liviubucel.com"

[[send_email]]
name = "EMAIL"
